# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('opening', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low', models.DecimalField(decimal_places=10, max_digits=20)),
                ('closing', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
