# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='cash',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioitem',
            unique_together=set([('portfolio', 'Item')]),
        ),
    ]
