# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171211_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='item',
        ),
    ]
