# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171211_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='items',
            field=models.ManyToManyField(to='api.Item'),
        ),
    ]
