# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171213_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('opening', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low', models.DecimalField(decimal_places=10, max_digits=20)),
                ('closing', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),

        migrations.RemoveField(
            model_name='item',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='item',
            name='high',
        ),
        migrations.RemoveField(
            model_name='item',
            name='low',
        ),
        migrations.RemoveField(
            model_name='item',
            name='opening',
        ),
        migrations.RemoveField(
            model_name='item',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='item',
            name='inst_type',
            field=models.CharField(default='empty', max_length=30),
            preserve_default=False,
        ),
        
    ]
