# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171213_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
